name: movies_app_train
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  animate_do: ^2.1.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  animated_text_kit: ^4.2.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.0.0
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  google_sign_in: ^5.4.1
  provider: ^6.0.3
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.3+1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
