// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADB_LhCFdL9VDCNfj8fqUyf-5StaAVtAs',
    appId: '1:384647350476:web:68a29d5bb0e2b6d5319a69',
    messagingSenderId: '384647350476',
    projectId: 'hoshows',
    authDomain: 'hoshows.firebaseapp.com',
    storageBucket: 'hoshows.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFf9X4bGliOxJhdGFSE4TA23rWo8_3o4',
    appId: '1:384647350476:android:80dfce00fcebdb93319a69',
    messagingSenderId: '384647350476',
    projectId: 'hoshows',
    storageBucket: 'hoshows.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8x-_4Pl6uHYu3ckxhNewNqP0CPF_lqI8',
    appId: '1:384647350476:ios:261d509f6a366fe3319a69',
    messagingSenderId: '384647350476',
    projectId: 'hoshows',
    storageBucket: 'hoshows.appspot.com',
    iosClientId: '384647350476-ojblpjnd3hk5j2kjbkrf36vngvjh9qbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesAppTrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8x-_4Pl6uHYu3ckxhNewNqP0CPF_lqI8',
    appId: '1:384647350476:ios:261d509f6a366fe3319a69',
    messagingSenderId: '384647350476',
    projectId: 'hoshows',
    storageBucket: 'hoshows.appspot.com',
    iosClientId: '384647350476-ojblpjnd3hk5j2kjbkrf36vngvjh9qbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesAppTrain',
  );
}
